M48
; DRILL file {KiCad 7.0.7} date Wed Sep 20 12:31:02 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-20T12:31:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X6.6469Y-4.0012
X6.6969Y-4.0012
X6.7469Y-4.0012
X6.7969Y-4.0012
X6.8469Y-4.0012
T0
M30
